### ISSUE TITLE
textmate remote: undefined method `[]'

### ISSUE THREAD

**Issue by threadhead** [wycats/textmate#3]
When executing the following command:

```
textmate remote
```

The following error is received:

```
/opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:29:in `remote': undefined method `[]' for nil:NilClass (NoMethodError)
from /opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:25:in `map'
from /opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:25:in `remote'
from /opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:16:in `each'
from /opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:16:in `remote'
from /opt/local/lib/ruby/gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `send'
from /opt/local/lib/ruby/gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `run'
from /opt/local/lib/ruby/gems/1.8/gems/thor-0.9.9/lib/thor/task.rb:20:in `parse'
from /opt/local/lib/ruby/gems/1.8/gems/thor-0.9.9/lib/thor.rb:78:in `start'
from /opt/local/lib/ruby/gems/1.8/gems/wycats-textmate-0.9.2/bin/textmate:218
from /opt/local/bin/textmate:19:in `load'
from /opt/local/bin/textmate:19
```

**Comment by wycats** [comment]
This is fixed on latest.
