### ISSUE TITLE
No remote task? Ruby 1.9 error?

### ISSUE THREAD

**Issue by kristianmandrup** [wycats/textmate#8]
$ textmate remote
The textmate_installer namespace doesn't have a 'remote' task

$ textmate install AppleScript GitHub
/Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/task.rb:90:in `parse_argument_error': uninitialized constant Thor::Group (NameError)
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/task.rb:35:in`rescue in run'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/task.rb:31:in `run'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/invocation.rb:108:in`block in invoke'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/invocation.rb:115:in `call'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/invocation.rb:115:in`invoke'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor.rb:137:in `block in start'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor/base.rb:369:in`start'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/thor-0.13.0/lib/thor.rb:124:in `start'
    from /Users/kristianconsult/.gem/ruby/1.9.1/gems/wycats-textmate-0.9.6/bin/textmate:264:in`<top (required)>'
    from /Users/kristianconsult/.gem/ruby/1.9.1/bin/textmate:19:in `load'
    from /Users/kristianconsult/.gem/ruby/1.9.1/bin/textmate:19:in`<main>'

**Comment by ghost** [comment]
Getting the same thing.
