### ISSUE TITLE
Ruby 1.9.1 and 1.9.2-preview3 issues using rvm

### ISSUE THREAD

**Issue by delwyn** [wycats/textmate#9]
Works fine with 1.8.7 using rvm. Both 1.9.1 and 1.9.2 raise the following error.

~/.rvm/gems/ruby-1.9.1-p378/gems/textmate-0.9.6/bin/textmate:22:in `block in search': undefined method`map' for #String:0x00000100cf6638 (NoMethodError)

**Comment by robsonpeixoto** [comment]
The same problem with ruby-1.9.3-p125.

/Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/textmate-0.9.6/bin/textmate:22:in `block in search': undefined method`map' for #String:0x007f853a12b378 (NoMethodError)
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/textmate-0.9.6/bin/textmate:17:in `each'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/textmate-0.9.6/bin/textmate:17:in`search'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/gems/textmate-0.9.6/bin/textmate:264:in `<top (required)>'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/bin/textmate:19:in`load'
    from /Users/robinho/.rvm/gems/ruby-1.9.3-p125/bin/textmate:19:in `<main>'
